[package]
name = "onion_peel"
version = "0.1.0"
authors = ["casept <davids.paskevics@gmail.com>"]
edition = "2018"

[dependencies]
ring = "~0"
byteorder = "~1"

[profile.dev]
opt-level = 0
debug = true

[dev-dependencies]
socks5_frontend = { git = "https://github.com/casept/socks5_frontend"}
