[package]
name = "onion_peel"
version = "0.1.0"
authors = ["casept <davids.paskevics@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 0
debug = true

[dev-dependencies]
socks5_frontend = { path = "../socks5_frontend"}