[package]
name = "onion_peel"
version = "0.1.1"
authors = ["casept <davids.paskevics@gmail.com>"]
edition = "2021"

[dependencies]
ring = "~0"

[profile.dev]
opt-level = 0
debug = true

[dev-dependencies]
socks5_frontend = { git = "https://github.com/casept/socks5_frontend"}
